Feat/mypage
B-I-G-team/big_front pull request #14
Opened 2023-03-29 10:19 UTC by AdolphKim

# What is this PR? 🔍

- 서비스 스펙 : "내 정보" 페이지 구성

# Changes 📝

어떤 작업을 했는지 세부적인 내용을 작성해 주세요.

1. 내 정보 구성
2. 내 예약정보 구성

# Screenshot 📷

| 기능 |                                                    스크린샷                                                     |
| :--: | :-------------------------------------------------------------------------------------------------------------: |
| 내 정보  | ![image](https://user-images.githubusercontent.com/80530044/228502643-110a51de-bef0-4472-9046-301f41cb313e.png)
|예약 정보| ![image](https://user-images.githubusercontent.com/80530044/228503584-3f8943f6-6183-426c-a6e3-783bb7795ea1.png)

# Test Checklist ☑️

# ETC 📎

현재는 더미데이터로 구성중이나 추후 백엔드와 연계하여 렌더링 할 예정입니다.

2023-04-09 06:24 UTC, daehwan2 requested changes
수고많으셨습니다!

현재 모바일반응형 작업진행중이라고 알고 있는데 작업이 끝나면 코멘트 달아주면 확인해보겠습니다!

그리고 현재 모든 데이터가 Reserve 컴포넌트내에 있고, 데이터의 key값으로 구분을 해서 렌더링을 해주고 있습니다. 그렇게 되다보니 Reserve 컴포넌트내에 렌더링 조건이 많이 걸려 있게 되어 버렸는데,
이는 더미데이터를 분리하면서 해결할 수 있을거라 생각이 듭니다!

코멘트 한번 확인해보시고 혹시 저와 생각이 다르다면 안바꾸시고 의견말씀해주셔도 됩니다!

2023-04-09 06:24 UTC, daehwan2 commented on src/container/mypage/index.tsx
> +};
따로 `components/mypage/ReserveState.tsx` 와 같은 파일로 빼는 건 어떨까요?
Notification 이라는 antd 컴포넌트가 있어서 중복될 것 같아서 위와 같은 컴포넌트 이름으로 변경하고 다른 파일로 분리하면 더 좋을 것 같다는 생각이듭니다!

그리고 any 타입을 구체화 시켜보는건 어떨까요?

그리고 마지막 else 는 아무런 의미가 없어보입니다!

```typescript
if (data === WAIT_CONFIRM) {
    return <Notify>😊 사장님의 승인요청을 기다리고 있습니다.</Notify>;
  } else if (data === WAIT_PAY) {
    return <Notify>😊 결제가 완료되면 예약이 완료됩니다.</Notify>;
  }
  return <></>;
```

이렇게 쓰는건 어떨까요?

2023-04-09 06:24 UTC, daehwan2 commented on src/components/mypage/Reserve.tsx
> +          </ReserveLabel>
여기는 제가 antd 의 tag 컴포넌트를 사용하는 걸로 디자인 해놓았습니다!
```javascript

import { Tag } from 'antd';
import { CheckCircleOutlined } from '@ant-design/icons';

...

<Tag icon={<CheckCircleOutlined />} color="success">
            예약완료
          </Tag>
```

참고 사이트
https://ant.design/components/tag

2023-04-09 06:24 UTC, daehwan2 commented on src/components/mypage/Reserve.tsx
> +          }
여기도 className 으로 스타일을 변경하는것보다는,
styled-components 의 props 를 넘겨주어서 처리하는 방식이 가독성 측면에서 더 좋을 것 같습니다. 
예를 들면,
```typescript
<ReserveInfoBox 
     active={data === el.type && subData === el.state} />

...

const ReserveInfoBox = styled.div<{active:boolean}>`
  color: ${({active})=> active ? 'green':'red'}
`
```

이런식으로 사용해보시는건 어떨까요?

2023-04-09 06:25 UTC, daehwan2 commented on src/container/mypage/index.tsx
> +                <Reserve Data={tab.content} subData={state}></Reserve>
다른 모든 컴포넌트에도 적용해주시면 감사하겠습니다!

2023-04-09 06:26 UTC, daehwan2 commented on src/container/mypage/index.tsx
> +};
한 파일에는 한개의 컴포넌트만 선언하는 걸로 규칙을 정했으면 좋겠습니다. 😀

2023-04-09 06:27 UTC, daehwan2 commented
추가적으로 모바일 반응형과 수정이 끝나면 머지를 할 예정입니다. api 가 생기면 다시 브랜치따서 작업을 하면 될것같습니다~

2023-04-13 11:56 UTC, AdolphKim commented on prisma/big.crt
> +-----END CERTIFICATE-----
삭제하겠습니다

2023-05-01 06:40 UTC, AdolphKim commented
마무리 했습니다. 확인후 머지 부탁드립니다 !

2023-05-02 15:29 UTC, daehwan2 commented
<img width="430" alt="image" src="https://user-images.githubusercontent.com/53414542/235712745-2662ba4f-1118-4c7e-aac8-4c5ba30b18b0.png">

@AdolphKim 모바일에서 스타일이 조금 깨져보이는 것 같은데 스타일 관련해서는 일일이 코멘트 달기보다는,, 제가 추후 작업을 해도될까요..?

2023-05-04 10:32 UTC, daehwan2 commented
@AdolphKim 스타일 수정 및 코드 정리를 좀 하였습니다.

수고많으셨습니다. 예약정보 관련한 부분의 코드를 제대로 다시 봤는데
예약 정보 전체 데이터의 타입을 가지고 css 로 보였다 안보였다 처리를 하고 있더라고요!
그렇게 하기보다는 .. 데이터 자체를 필터링 하는게 더 좋아보이네요. 이는 이쪽 api가 생기고 나서 추후 작업을 하면 좋을 것 같습니다.

확인 코멘트 주시면 일단 머지하겠습니다~

2023-05-04 11:23 UTC, daehwan2 approved these changes
수고하셨습니다! 테스트 및 리뷰 완료하였습니다. 👏

2023-05-04 11:23 UTC, merged